server:
  port: 8099
  servlet:
    context-path: /hsrt-ll-api
#链接数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_hsrt?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB         #文件最大限制
      max-request-size: 10MB      #请求最大限制
  web:
    resources:
      static-locations: file:${oss.local.upload-file-path}  #配置有地址映射本地静态资源
path:
  uploadPath: http://127.0.0.1:8099/hsrt-ll-api
oss:
  local:
    domain: 本地地址
    #    upload-file-path: /root/project_file
    upload-file-path: E:/project_file